(<class 'AttributeError'>, AttributeError("module 'os' has no attribute 'IOError'"), <traceback object at 0x7fe8d0a4dd40>)
[<FrameSummary file main.py, line 8 in <module>>, <FrameSummary file /home/runner/Microsystems/system.py, line 214 in start>, <FrameSummary file /home/runner/Microsystems/filesystem.py, line 15 in readFile>]